/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplos;

import captura.ICapturaVideoUI;
import java.util.Observer;

/**
 *
 * @author robertosilva
 */
public class CorrespondenciaForcaBrutaUI extends javax.swing.JPanelimplements ICapturaVideoUI, Observer {

    /**
     * Creates new form CorrespondenciaForcaBrutaUI
     */
    public CorrespondenciaForcaBrutaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sldHisterese1 = new javax.swing.JSlider();
        spnHisterese1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        radImgOriginal = new javax.swing.JRadioButton();
        radImgContorno = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detecção de contorno (Bordas de Canny)"));
        jPanel1.setLayout(new java.awt.GridLayout(0, 3, 5, 5));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("1º limiar histerese");
        jPanel1.add(jLabel4);

        sldHisterese1.setMaximum(2000);
        sldHisterese1.setMinimum(1);
        sldHisterese1.setValue(600);
        sldHisterese1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldHisterese1StateChanged(evt);
            }
        });
        jPanel1.add(sldHisterese1);

        spnHisterese1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnHisterese1StateChanged(evt);
            }
        });
        jPanel1.add(spnHisterese1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        radImgOriginal.setSelected(true);
        radImgOriginal.setText("Original");
        radImgOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radImgOriginalItemStateChanged(evt);
            }
        });
        jPanel3.add(radImgOriginal);

        radImgContorno.setText("Contorno");
        radImgContorno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radImgContornoItemStateChanged(evt);
            }
        });
        jPanel3.add(radImgContorno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sldHisterese1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldHisterese1StateChanged
        
    }//GEN-LAST:event_sldHisterese1StateChanged

    private void spnHisterese1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnHisterese1StateChanged
        
    }//GEN-LAST:event_spnHisterese1StateChanged

    private void radImgOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radImgOriginalItemStateChanged
       
    }//GEN-LAST:event_radImgOriginalItemStateChanged

    private void radImgContornoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radImgContornoItemStateChanged
        
    }//GEN-LAST:event_radImgContornoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radImgContorno;
    private javax.swing.JRadioButton radImgOriginal;
    private javax.swing.JSlider sldHisterese1;
    private javax.swing.JSpinner spnHisterese1;
    // End of variables declaration//GEN-END:variables
}
