/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplos;

import captura.ICapturaVideoUI;
import java.awt.image.BufferedImage;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;
import util.JPanelImageUtil;

/**
 *
 * @author Roberto
 */
public class DesfocagemGaussianaUI extends javax.swing.JPanel implements ICapturaVideoUI, Observer {

    private JPanel pnlExibicao;
    private DesfocagemGaussiana obj;
    private boolean camDisponivel;
    private boolean renderizaMiniaturaProcessada;

    /**
     * Creates new form DesfocagemGaussianaUI
     */
    public DesfocagemGaussianaUI() {
        initComponents();

        obj = new DesfocagemGaussiana();
        obj.addObserver(this);

        sldSigmaX.setValue((int) obj.getSigmaX());
        sldSigmaY.setValue((int) obj.getSigmaY());
        sldTamanhoX.setValue(obj.getTamanhoX());
        sldTamanhoY.setValue(obj.getTamanhoY());
        
        spnSigmaX.setValue((int) obj.getSigmaX());
        spnSigmaY.setValue((int) obj.getSigmaY());
        spnTamanhoX.setValue(obj.getTamanhoX());
        spnTamanhoY.setValue(obj.getTamanhoY());

        camDisponivel = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sldSigmaX = new javax.swing.JSlider();
        spnSigmaX = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        sldSigmaY = new javax.swing.JSlider();
        spnSigmaY = new javax.swing.JSpinner();
        lblSobel = new javax.swing.JLabel();
        sldTamanhoX = new javax.swing.JSlider();
        spnTamanhoX = new javax.swing.JSpinner();
        lblSobel1 = new javax.swing.JLabel();
        sldTamanhoY = new javax.swing.JSlider();
        spnTamanhoY = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(360, 102));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes de desfoque"));
        jPanel1.setLayout(new java.awt.GridLayout(0, 3, 5, 5));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sigma X");
        jPanel1.add(jLabel4);

        sldSigmaX.setMinimum(1);
        sldSigmaX.setValue(1);
        sldSigmaX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSigmaXStateChanged(evt);
            }
        });
        jPanel1.add(sldSigmaX);

        spnSigmaX.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnSigmaX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSigmaXStateChanged(evt);
            }
        });
        jPanel1.add(spnSigmaX);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sigma Y");
        jPanel1.add(jLabel5);

        sldSigmaY.setMinimum(1);
        sldSigmaY.setValue(1);
        sldSigmaY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSigmaYStateChanged(evt);
            }
        });
        jPanel1.add(sldSigmaY);

        spnSigmaY.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnSigmaY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSigmaYStateChanged(evt);
            }
        });
        jPanel1.add(spnSigmaY);

        lblSobel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSobel.setText("Tamanho X");
        jPanel1.add(lblSobel);

        sldTamanhoX.setMaximum(255);
        sldTamanhoX.setMinimum(1);
        sldTamanhoX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldTamanhoXStateChanged(evt);
            }
        });
        jPanel1.add(sldTamanhoX);

        spnTamanhoX.setModel(new javax.swing.SpinnerNumberModel(7, 1, 500, 2));
        spnTamanhoX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTamanhoXStateChanged(evt);
            }
        });
        jPanel1.add(spnTamanhoX);

        lblSobel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSobel1.setText("Tamanho Y");
        jPanel1.add(lblSobel1);

        sldTamanhoY.setMaximum(255);
        sldTamanhoY.setMinimum(1);
        sldTamanhoY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldTamanhoYStateChanged(evt);
            }
        });
        jPanel1.add(sldTamanhoY);

        spnTamanhoY.setModel(new javax.swing.SpinnerNumberModel(7, 1, 500, 2));
        spnTamanhoY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTamanhoYStateChanged(evt);
            }
        });
        jPanel1.add(spnTamanhoY);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void sldSigmaXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSigmaXStateChanged
        int vl = (int) sldSigmaX.getValue();
        obj.setSigmaX(vl);
        spnSigmaX.setValue(vl);
    }//GEN-LAST:event_sldSigmaXStateChanged

    private void spnSigmaXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSigmaXStateChanged
        int vl = (int) spnSigmaX.getValue();
        obj.setSigmaX(vl);
        sldSigmaX.setValue(vl);
    }//GEN-LAST:event_spnSigmaXStateChanged

    private void sldSigmaYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSigmaYStateChanged
        int vl = (int) sldSigmaY.getValue();
        obj.setSigmaY(vl);
        spnSigmaY.setValue(vl);
    }//GEN-LAST:event_sldSigmaYStateChanged

    private void spnSigmaYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSigmaYStateChanged
        int vl = (int) spnSigmaY.getValue();
        obj.setSigmaY(vl);
        sldSigmaY.setValue(vl);
    }//GEN-LAST:event_spnSigmaYStateChanged

    private void sldTamanhoXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldTamanhoXStateChanged
        int vl = obtemValorImpar(obj.getTamanhoX(), (int) sldTamanhoX.getValue());
        obj.setTamanhoX(vl);
        spnTamanhoX.setValue(vl);
    }//GEN-LAST:event_sldTamanhoXStateChanged

    private void spnTamanhoXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTamanhoXStateChanged
        int vl = (int) spnTamanhoX.getValue();
        obj.setTamanhoX(vl);
        sldTamanhoX.setValue(vl);
    }//GEN-LAST:event_spnTamanhoXStateChanged

    private void sldTamanhoYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldTamanhoYStateChanged
        int vl = obtemValorImpar(obj.getTamanhoY(), (int) sldTamanhoY.getValue());
        obj.setTamanhoY(vl);
        spnTamanhoY.setValue(vl);
    }//GEN-LAST:event_sldTamanhoYStateChanged

    private void spnTamanhoYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTamanhoYStateChanged
        int vl = (int) spnTamanhoY.getValue();
        obj.setTamanhoY(vl);
        sldTamanhoY.setValue(vl);
    }//GEN-LAST:event_spnTamanhoYStateChanged

    // <editor-fold defaultstate="collapsed" desc="Métodos herdados">
    @Override
    public boolean cameraDisponivel() {
        return camDisponivel;
    }

    @Override
    public void iniciar() {
        obj.iniciarCaptura();
    }

    @Override
    public void parar() {
        obj.pararCaptura();
    }

    @Override
    public void setPainelExibicao(JPanel painel) {
        pnlExibicao = painel;
    }

    @Override
    public void setRenderizaMiniaturaProcessada(boolean renderizaMiniaturaProcessada) {
        this.renderizaMiniaturaProcessada = renderizaMiniaturaProcessada;
    }

    @Override
    public void update(Observable o, Object arg) {
        BufferedImage[] bufImgs = (BufferedImage[]) arg;
        
        JPanelImageUtil.drawImageWithAspectRatio(pnlExibicao, bufImgs[1]);
        
        camDisponivel = true;
    }
    // </editor-fold>
    
    private int obtemValorImpar(int valorRef, int valorAlvo){
        if(valorAlvo > valorRef && valorAlvo % 2 ==0)
            valorAlvo++;
        else if(valorAlvo < valorRef && valorAlvo % 2 ==0)
            valorAlvo--;
        else if(valorAlvo % 2 ==0)
            valorAlvo = valorAlvo <= 2 ? 1 : --valorAlvo;
                
        return valorAlvo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSobel;
    private javax.swing.JLabel lblSobel1;
    private javax.swing.JSlider sldSigmaX;
    private javax.swing.JSlider sldSigmaY;
    private javax.swing.JSlider sldTamanhoX;
    private javax.swing.JSlider sldTamanhoY;
    private javax.swing.JSpinner spnSigmaX;
    private javax.swing.JSpinner spnSigmaY;
    private javax.swing.JSpinner spnTamanhoX;
    private javax.swing.JSpinner spnTamanhoY;
    // End of variables declaration//GEN-END:variables
}
